WeblateOrg/docker

weblate/Dockerfile

this is old change i had laying around. should fix using svn over git-svn package.
as i recall git-svn package does not pull svn client itself somewhy

add subversion client

---

README.md
docker-compose.yml

fixes https://github.com/nijel/weblate/issues/1277
if any port should be overridden, that should be for `web` container

do not suggest to map weblate ports

---

weblate/Dockerfile
weblate/settings.py

Install hub inside the weblate container and expose `GITHUB_USERNAME` through an environment variable.

Add github pull requests support

---

.docker-ignore
.dockerignore

1. correct filename is .dockerignore
2. syntax is not same as .gitignore, remove leading slashes
https://docs.docker.com/engine/reference/builder/#dockerignore-file

fix docker ignore

---

Dockerfile
requirements.txt
settings.py

based on documentation:
https://docs.weblate.org/en/latest/admin/auth.html#ldap-authentication
second part goes to master branch: https://github.com/WeblateOrg/docker/pull/54

add ldap auth support

---

environment

requires ldap changes for docker image:
https://github.com/WeblateOrg/docker/pull/53

add ldap auth env examples

---

environment

This PR adds two new environment variables which will be used to configure memcached.

Add environment variables for memcached

---

Dockerfile
crontab.txt
settings.py
start
supervisor.conf

run cron jobs in docker

---

settings.py

adds consistency with `get_env_list`

settings.py: return default in get_env_map

---

README.md

i'm paranoid. i want to use immutable tags when setting up local deployment.

readme: add link where to look for specific tags

---

Dockerfile
settings.py
weblate.uwsgi.ini

That should give us newer Python version to address
https://bugs.python.org/issue29519

Base on Ubuntu

---

start

Pull request for fixing issue #108

Fix for #108 - Added REDIS_ to list for profile export

---

etc/weblate/settings.py

Fixes #107. Successfully tested.

Add LDAP user bind config

---

etc/weblate/settings.py

I'm not a python developer, so I'm not sure if setting this to an undefined value will break things...

add sslmode setting

---

Dockerfile
etc/uwsgi/apps-enabled/weblate.ini
etc/weblate/settings.py

It is upcoming stable release and it should perform better thanks to
Python 3.7.

Switch base to Debian Buster

---

Dockerfile
etc/nginx/default.tpl
etc/supervisor/conf.d/weblate.conf
etc/uwsgi/apps-enabled/weblate.ini
start

Based on https://github.com/WeblateOrg/docker/pull/293

Run image as non root

---

Dockerfile
etc/supervisor/conf.d/weblate.conf
etc/supervisor/supervisord.conf

Issue #326
See https://stackoverflow.com/a/21371113/225718

Use supervisor-stdout to handle stdout redirection

---

.travis.yml
Dockerfile
etc/nginx/run.sh
etc/nginx/ssl.tpl

Add support for SSL certs

---

Dockerfile
requirements.txt

Those seem to be reinstalled anyway, so avoid having them twice.

Install more deps using pip

---

Dockerfile

Needed for compatibility with 13 server.

Install postgresql client 13

---

.github/bin/get-buildx-args

Making it easier to find version published at some time.

CI: Add named tag to edge and bleeding builts

---

etc/nginx/default.tpl
etc/nginx/ssl.tpl
start

For context, see: https://github.com/WeblateOrg/docker/commit/7b8640152caf95b1955813a482719d20a911aea0#r43335920
~~This is a placeholder. I haven't tested it yet due to the lack of time.~~

Revert: "nginx: Properly redirect non matching domains"

---

README.md

Before submitting a pull request, please ensure that:

Remove specific markdownlint configuration

---

.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml

This provides more fine grained control and output in GitHub.

Use steps based testing

---

Dockerfile

It is needed for recent cryptography, see #953

Include rust compiler in the build environment

---

Dockerfile
start

Looking at the tzdata code, the /etc/localtime is not updated if
/etc/timezone is not present.
Fixes #960

Prevent dpkg to update /etc/localtime

---

Dockerfile

This might be a better workaround than setting environment variable, see
https://github.com/balena-io-library/base-images/issues/562

Run c_rehash to fix SSL issues

---

.github/workflows/dockerimage.yml
.gitmodules
Dockerfile
etc/nginx/default.tpl
etc/nginx/ssl.tpl
patches/0001-Docker-Move-static-files-to-separate-volume.patch
start

This is still not full scaling as this still needs a single web
container.
Fixes #683
Issue #700

Allow to run only defined services

---

start

Use upper and lower bounds to avoid spawning too many processes.
The best solution would be to base this on actual resources available
to the container, but I have no clue how to figure out these.
Fixes https://github.com/WeblateOrg/helm/issues/83

Autoscale number of processes

---

start

It is used in the settings and ping commands fail without it.
Fixes #1078

start: Generate SAML certificate earlier and only when needed

---

Dockerfile
etc/uwsgi/apps-enabled/weblate.ini

Update to Debian 11 Bullseye

---

Dockerfile
requirements.txt

It depends on libffi which might be not compatible with the wheel.
Fixes #1222

deps: Avoid using binary packages for cffi

---

.github/bin/get-buildx-args
.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml
Dockerfile

Workaround rust/cargo issues by installing older cryptography from     wheel.
Fixes  #968

ci: Bring back arm/v7 build

---

.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml
Dockerfile

That seems to workaround https://github.com/rust-lang/cargo/issues/8719.

build: Use tmpfs for cargo cache

---

start

PostgreSQL 9.6 is no longer supported, so give user a clear error message in such case.
Fixes #1314

start: Check for PostgreSQL version

---

Dockerfile

This allows us to get newer Python with improved performance.

Use Python base image instead of Debian

---

.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml

Let somebody else maintain the workaround, see https://github.com/rust-lang/cargo/issues/8719#issuecomment-1068957566

ci: Use JonasAlfredsson/docker-on-tmpfs instead of own code

---

.github/bin/get-buildx-args
.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml
Dockerfile

- The rustup is again broken on armv7
- Remove rust installation and
- Use binary wheels for cryptography it has arm64 and x86_64.

docker: Drop armv7

---

Dockerfile

Bumps python from 3.10.7-slim-bullseye to 3.11.0-slim-bullseye.
---
updated-dependencies:
- dependency-name: python dependency-type: direct:production update-type: version-update:semver-minor ...
Signed-off-by: dependabot[bot] <support@github.com>

build(deps): bump python

---

Dockerfile

Sounds better than placing them in /usr/src/

dockerfile: Move sources to /app/src

---

Dockerfile
start

This should allow read-only root filesystem.
Fixes #1831

nginx: Generate configuration file in /tmp

---

Dockerfile
start

docker: Write timezone to /tmp

---

.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml

ci: Test both read-only and read-write container setup

---

Dockerfile
requirements.txt

Weblate 5.x tesseract changes, see https://github.com/WeblateOrg/weblate/pull/9606

Tesseract in Weblate 5.0

---

Dockerfile

dockerfile: update to Debian 12

---

Dockerfile

This should be no longer needed with tesserocr arm64 wheels.

dockerfile: drop libtesseract5

---

Dockerfile

- en_US.UTF-8 locales are needed for Python 3.12 for proper collation
- the c.UTF-8 collation no longer does work as Unicode
- This switches back to en_US.UTF-8 locales inside container because we need it anyway for Python

packages: Include locales

---

.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml

This allows us to addopt new features once available, see #5399

ci: pin buildx version

---

.github/bin/docker-build
.github/bin/get-buildx-args
.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml

This needs --annotations support in buildx which was introduced in https://github.com/docker/buildx/pull/2020 and will be released in 0.12.0.

build: include annotations in the multi-arch images

---

Dockerfile
Gemfile

We do not need latest version and this one is easier to install.

dockerfile: install licensee using apt

---

etc/supervisor/supervisord.conf
start

This allows changing it even on the read-only filesystem.
See #2420

feat(start): move supervisor configuration to /run

---

.github/workflows/dockerimage.yml
etc/supervisor/conf.d/celery-single.conf
start

Followup to https://github.com/WeblateOrg/docker/pull/2420

feat: Add option to use one celery process

---

Dockerfile

Not for merge, see https://github.com/astral-sh/uv/issues/6105

debug uv invocation (not for merge)

---

.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml

- this verifies that merging actually works before doing publish
- can be later used for proper merge as described in #2589

feat(ci): add merge step to CI pipeline

---

Dockerfile

This creates an independent layer which can be more effectively cached.
See https://github.com/moby/buildkit/blob/dockerfile/1.4.3/frontend/dockerfile/docs/syntax.md#linked-copies-copy---link-add---link

chore(dockerfile): use --link to copy files

---

.github/bin/bleeding
.github/bin/get-buildx-args

This fixes the published revision while repo is changing during the build.

fix(ci): use initial SHA and date when publishing

---

.github/workflows/bleeding.yml

The old approach is deprecated for quite some time, see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

fix(ci): use environment files to get outputs

---

.github/bin/get-buildx-args
.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml

See https://docs.docker.com/build/ci/github-actions/cache/

feat(ci): use GitHub Actions cache instead of doing that manually

---

Dockerfile

It should not be needed anymore.

fix(Dockerfile): avoid separate step for instaling cffi

---

Dockerfile

The version 17 client is needed to dump version 17 server.

feat(deps): PostgreSQL 17 compatibility

---

Dockerfile
requirements.txt

- avoids mixing up Weblate and supervisor deps in single venv
- makes the supervisor available earlier

chore: use supervisor from base image

---

etc/supervisor/conf.d/web.conf
start

This reduces memory usage and improves performance.

feat: utilize gunicorn threads

---

.github/workflows/container-build.yml

feat(ci): use native arm64 builds

---

.github/workflows/container-build.yml
Dockerfile

chore: debug uv cache use

---

.github/bin/get-buildx-args
.github/workflows/container-build.yml
.github/workflows/container-ci.yml
.github/workflows/container-test.yml

Unlike GitHub Actions Cache this doesn't expire and it will be preserved while the job is running.
Fixes #2589

feat: utilize artifacts for sharing build cache

---

.github/workflows/container-ci.yml

With proper caching and artifacts sharing the indivdual jobs run much faster and the slowest operation now are sequential execution of the tests. Let's execute them in parallel.

chore(ci): run all tests in parallel

---

.github/bin/get-buildx-args

The local cache is discarded in this step, so there is no need to generate it.

chore(ci): disable storing to local cache on load

---

health_check

It is executed every 30 seconds so there is no use to keep the probe running longer.

feat: add timeout to health check

---

start

fix: use venv python to generate secret

---

.github/workflows/container-test.yml

feat: list versions from the Weblate container

---

Dockerfile

The secret key in that just trigger security scanners and we have no use for the test data.
See https://github.com/python-ldap/python-ldap/issues/557

fix: remove slapdtest from the image

---

Dockerfile

chore(deps): update weblate/dev docker tag to v2025.16.2

---

Dockerfile

chore(deps): update weblate/base docker tag to v2025.16.1

---

etc/nginx/nginx.conf

This is anyway overrided in the SSL setup, but make sure the server-wide defaults are safe as well.

fix(nginx): modernize ssl protocols

---

Dockerfile

chore: use standard renovate annotation

---

.github/workflows/container-ci.yml
etc/nginx/default.tpl
etc/nginx/generate-site.py
start

This seems the most effective way to localy fight AI traffic these days.

feat(nginx): add support for integrating anubis

---

etc/nginx/default.tpl
etc/nginx/generate-site.py
start

fix(nginx): correct redirect URL for anubis

---

etc/supervisor/conf.d/celery-backup.conf
etc/supervisor/conf.d/celery-celery.conf
etc/supervisor/conf.d/celery-memory.conf
etc/supervisor/conf.d/celery-notify.conf
etc/supervisor/conf.d/celery-translate.conf

This reduces memory usage of the container.

feat: use threads pool in Celery

---

requirements.txt

chore(deps): remove no longer needed Python deps

---

Dockerfile

This could possibly leave stale lock files in /tmp which we do not want in the container.

feat: use tmpfs during uv packages install

---

.github/bin/bleeding
.pre-commit-config.yaml
Dockerfile
patches/0001-feat-accounts-rely-on-social-auth-session-restore-15.patch

Without that the OpenID flow is sometimes broken.

fix: backport social-auth compatibility

---

patches/0001-Revert-feat-add-PWA-support-with-caching-and-offline.patch

It seems to cause weird issues when downloading large files (such as project backups).

fix: revert ServiceWorker integration

---

etc/supervisor/conf.d/celery-backup.conf
etc/supervisor/conf.d/celery-beat.conf
etc/supervisor/conf.d/celery-celery.conf
etc/supervisor/conf.d/celery-memory.conf
etc/supervisor/conf.d/celery-notify.conf
etc/supervisor/conf.d/celery-single.conf
etc/supervisor/conf.d/celery-translate.conf
etc/supervisor/conf.d/check.conf
etc/supervisor/conf.d/web.conf
etc/supervisor/supervisord.conf

This removes dependency on the unmaintained supervisor plugin.

fix: stop using events for stdout redirection

---

.github/workflows/container-test.yml

There seems to be a gunicorn issue that it fails upon restart, add test convering this.
Issue #3507

feat(ci): add tests for repeating requests

---

etc/nginx/default.tpl
etc/supervisor/conf.d/web.conf

The warning sounds scary, so avoid that feature for now and use TCP instead.

chore: avoid using experimental uds in granian
