WeblateOrg/docker

weblate/environment

Quotes in environment variables result in issues, because they are directly passed to the python variables.

removed quotes and spaces

---

README.md

fix `docker-compose.override.yml` error under docker-compose 1.8.0:
```
ERROR: Version mismatch: file ./docker-compose.yml specifies version 2.0 but extension file ./docker-compose.override.yml uses version 1
```

upgrade override.yml to 2.0

---

weblate/Dockerfile

in certain setups where umask is not `002` resulting image contains script that is not world accessible:
```
weblate@64e68f4a8aa1:/tmp$ ls -l /app/bin/start 
-rwxrwx--x 1 root root 322 Sep  6 06:09 /app/bin/start
```
this results unusable container:
```
/bin/sh: 0: Can't open /app/bin/start
```

fix ADD-ed files permissions

---

README.md

```
Postgres is up
You have requested to collect static files at the destination
location as specified in your settings:
/app/data/static
This will overwrite existing files!
Are you sure you want to do this?
Type 'yes' to continue, or 'no' to cancel: ^C
```
after the change:
```
Postgres is up
Copying '/app/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/base.css'
Copying '/app/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/changelists.css'
Copying '/app/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/dashboard.css'
Copying '/app/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/fonts.css
...
Copying '/app/local/lib/python2.7/site-packages/weblate/static/js/mousetrap-global-bind.js'
Copying …
```

don't ask user for collectstatic

---

weblate/start

following discussion on 7f1b6b56a
thought why not just use Django itself, it's already installed!
example:
```
$ python -c "from django.utils.crypto import get_random_string; print get_random_string(50)"
KMiFcPMlVuBkwT0Z6MLqZB4jzAdrOQ5T2Q05n1ZNBUW5rGO4t1
```

use django own method to generate secret

---

weblate/Dockerfile

In order to enable YAML files in Weblate Docker container, the 'python-yaml' should be installed. Therefore I recommend to include this package into the Weblate Dockerfile.

Add python-yaml package definition to Weblate Dockerfile

---

weblate/Dockerfile

Official documentation (1) told us about SSH access.
This change allow us add ~/.ssh/id_rsa key easiest
(1) https://docs.weblate.org/en/weblate-2.9/faq.html#git-export

Add home directory for weblate user

---

settings.py
start

Hello, we have been deploying Weblate in our cluster and have noticed the inconvenience to be able to configure the database host. We already had a PostgreSQL instance and did not wish to use the specific one configured in the docker-compose file. Additionally, we are deploying with Kubernetes and Cloud SQL Proxy, so this was a nuisance.
With this PR users should be able to configure the host/port of their PostgreSQL instance.
Notice that if **POSTGRES_PORT** is not set, the script check will still work.
I don't understand the nature of the two branches, but since there's a dependency between them I created two related PRs.
Furthermore, I wanted to suggest to increase the sleep time of the database status check via psql, currently 1s is log cluttering.

Allow PostgreSQL host and port to be defined as environment variables

---

environment

DEPENDS ON: https://github.com/WeblateOrg/docker/pull/41
----
Hello, we have been deploying Weblate in our cluster and have noticed the inconvenience to be able to configure the database host. We already had a PostgreSQL instance and did not wish to use the specific one configured in the docker-compose file. Additionally, we are deploying with Kubernetes and Cloud SQL Proxy, so this was a nuisance.
With this PR users should be able to configure the host/port of their PostgreSQL instance.
Notice that if **POSTGRES_PORT** is not set, the script check will still work.
I don't understand the nature of the two branches, but since there's a dependency between them I created two related PRs.
Furthermore, I wanted to suggest to increase the sleep time of the database status check via psql, …

Added POSTGRES_HOST and POSTGRES_PORT to the environment list file

---

settings.py

Useful when the mail server is a local SMTP server with no auth
or encryption.

add WEBLATE_EMAIL_USE_TLS to match EMAIL_USE_TLS

---

settings.py

By default return URLs created by python-social-auth uses **http** links. It can be forced to use **https** URLs by setting `REDIRECT_IS_HTTPS` to `true`. This PR changes _settings.py_ in docker image to use `WEBLATE_ENABLE_HTTPS` environment variable for setting `REDIRECT_IS_HTTPS` value.
I have stumbled on this by trying to create **https** only weblate instance with Google authentication backend enabled. On the Google auth configuration I have white-listed only **https** address of the weblate instance and whole authentication workflow was failing until `REDIRECT_IS_HTTPS` was set to `true`.
More details in [python-social-auth-docs](http://python-social-auth-docs.readthedocs.io/en/latest/configuration/settings.html?highlight=REDIRECT_IS_HTTPS) section "Processing redirects and …

Set REDIRECT_IS_HTTPS to match ENABLE_HTTPS value

---

docker-compose.yml

Additionally, memcached:1.4 doesn't seem to be supported anymore: https://hub.docker.com/_/memcached/

Lighter alternatives to dependency images

---

docker-compose-https.yml

STAGE is staging by default, which results in a test (untrusted) certificate from Let's Encrypt.

minor docker-compose-https.yml example update for https-portal

---

start

This ensures that the command works if the default database named the
same as the user doesn't exist. It also makes more sense to check
connection to the database which we intend to use.

Add database flag to psql command

---

settings.py

This PR makes `settings.py` configure memcached based on the values of the environment variables `MEMCACHED_HOST` and `MEMCACHED_PORT`. This pull request depends on PR #61.

Make memcached host and port configurable through environment vars

---

settings.py

See https://docs.djangoproject.com/en/1.11/ref/settings/#email-use-ssl

add WEBLATE_EMAIL_USE_SSL to match EMAIL_USE_SSL

---

Dockerfile
requirements.txt
start
weblate.uwsgi.ini

Switch to Python 3

---

weblate.uwsgi.ini

fix `Resource temporarily unavailable` error
nginx error log:
```
[error] 19#19: *259 connect() to unix:/var/run/uwsgi/app/weblate/socket failed (11: Resource temporarily unavailable) while connecting to upstream, client: 10.0.1.181, server: ....
```

enable uwsgi harakiri mode and stats server

---

settings.py

Machine translations currently cannot be configured completely via Docker enviroment variables.
This PR adds `WEBLATE_MT_MYMEMORY_ENABLED` and `WEBLATE_MT_GLOSBE_ENABLED` in order to enable these services.

Enable Glosbe and MyMemory machine translations via enviroment variables

---

settings.py

Fix for #93
Use proper configuration option for a list of machine translations.
Use proper naming for modules

Fix for configuration of Machine Translations

---

etc/uwsgi/apps-enabled/weblate.ini

Rather than start 6 workers at start,  start 2,  and scale up as needed. 
This saves some memory on low traffic weblate installs

Scale uwsgi workers on demand

---

etc/weblate/settings.py

If weblate is running behind a proxy and is configured to redirect to HTTPS, `/healthz/` endpoint also becomes unavailable via good old HTTP for no good reason. This trips up some health check probes making them believe that the service is not available even when it in fact is. It is possible to work around this inconvenience by injecting `X-Forwarded-Proto: https` header but in some scenarios, even that is not feasible. Therefore I propose to just make `/healthz/` endpoint exempt from the SSL redirect. Optionally, we could parameterize it, too. 
More context: https://twitter.com/mareksuscak/status/1139661979516170240

Make /healthz/ endopint exempt from SSL redirect

---

etc/weblate/settings.py

Django [strips it away](https://github.com/django/django/blob/817c6cdf0e2a72362045ca503af01830df9b9d36/django/middleware/security.py#L21) for no obvious reason so the previous code wasn't working as expected.
UPDATE: 
We've just tested this patch and can confirm it works as expected in the Kubernetes environment.

Fix secure redirect URL pattern

---

etc/nginx/default.tpl
etc/nginx/run.sh
start

There are some infrastructure when the security policies in docker doesn't allow a process to expose the 80 port. In order to adapt those, I added an environment variable in order to allow the user to change the webserver port.

Add an env var for the web server port

---

etc/supervisor/conf.d/weblate.conf
requirements.txt

Before:
```
Tasks:  19 total,   1 running,  18 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   1694.6 total,    119.3 free,   1245.4 used,    330.0 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.    295.2 avail Mem
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1 root      20   0   26988  18684   5328 S   0.0   1.1   0:00.29 supervisord
119 weblate   20   0  222736 123188  21280 S   0.0   7.1   0:03.06 celery
120 weblate   20   0  221876 122176  20376 S   0.0   7.0   0:02.92 celery
122 weblate   20   0  222216 121724  22048 S   0.0   7.0   0:02.48 celery
123 weblate   20   0  222480 123296  21408 S   0.0   7.1   0:02.91 celery
124 weblate   20   0  222740 123488 …
```

save memory by using eventlet for celery workers

---

requirements.txt

I needed to add this to docker image, otherwise auth porviders using OpenID does not work. Explicitly I was testing with Auth0.com provider.
We've added this by hand to openshift deployment, but it makes sense to have it in docker also.

Add openid connect providers to requirements

---

Dockerfile
start

this fixes #467 
required for WeblateOrg/weblate#3318
To enable automated configuration of lab we introduce 2 new ENV variables
* **WEBLATE_GITLAB_HOST** 
default not set 
eg. https://gitlab.example.com
* **WEBLATE_GITLAB_TOKEN** 
default not set
should be a token you generated for your gitlab translation user
A PR for WeblateOrg/docker-compose and the Weblate docs will be created soon.

add lab binary and configuration by ENV variables

---

Dockerfile

Add libxmlsec1-openssl to runtime dependencies. This is needed by SAML auth

---

.github/workflows/dockerimage.yml

- build images natively and using buildx (to ensure that both approaches
work)
- store images in the registry
- test built images
- publish them once tested
Fixes #662

CI: Build images just once and share built images

---

.github/bin/bleeding
.github/bin/get-buildx-args
.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml

- build each architecture in separate job
- wait with tests only on amd64 builds
This should reduce overall time needed for CI.

Paralellize buildx jobs

---

etc/supervisor/supervisord.conf

I'm trying to deploy Weblate to a small server, and running into some memory pressure because of the number of Celery workers running. I noticed that the supervisord config explicitly sets concurrency for each worker. I think it would be better to let Celery default that value to the number of cores: https://docs.celeryproject.org/en/stable/reference/celery.bin.worker.html#cmdoption-celery-worker-c
In my case, that's only 2, but on much larger machines, someone might want to be able to increase it past 4 for more throughput.
I did not change the value where concurrency=1 was specified, because presumably that is an intentional "don't scale up with the number of cores" limit.

Don't specify concurrency except to limit it to 1

---

Dockerfile
etc/supervisor/supervisord.conf
start

now the user can pass arbitrary options to jobs with environment variables.
For example:
CELERY_MAIN_OPTIONS="--pool=gevent"
CELERY_NOTIFY_OPTIONS="--pool=gevent"
CELERY_TRANSLATE_OPTIONS="--pool=gevent"
CELERY_MEMORY_OPTIONS="--pool=gevent"
CELERY_BACKUP_OPTIONS="--pool=gevent"
CELERY_BEAT_OPTIONS="--pool=gevent"
This could serve as a safer and more flexible approach than #744

Allow user to pass arbitrary options to jobs

---

etc/uwsgi/apps-enabled/weblate.ini
start

UWSGI supports environment variables for all configuration,  as long as it is not hardcoded in weblate.ini.
This PR removes workers from weblate.ini. It will just use the default amount of workers.   A user of this image can specify the workers by adding this environment variable to the docker image:
```
UWSGI_WORKERS=8
```
Documentation is available at https://uwsgi-docs.readthedocs.io/en/latest/Configuration.html#environment-variables.
For small deployments one could do:
```
UWSGI_WORKERS=1
```
or just do nothing.
Before:
after:

feat: allow user to specify uwsgi workers

---

Dockerfile

This is needed for pg_dump compatibility with the 12 server.

Install PostgreSQL 12 client

---

etc/nginx/default.tpl
etc/nginx/ssl.tpl
start

This avoids DisallowedHost warnings.
Fixes #733

nginx: Properly redirect non matching domains

---

Dockerfile

The Dockerfile contains `EXPOSE 8080 8443`. This makes this Docker image unusable to be deployed on Cloud Foundry since Cloud Foundry only allows one port to be exposed.
This PR changes this to only expose `8080`.

Remove extra EXPOSE port in Dockerfile, resolves #863

---

start

See https://github.com/WeblateOrg/weblate/issues/10037

start: Avoid probing server version with WEBLATE_DATABASES=False

---

.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml
etc/supervisor/supervisord.conf
start

This is different than fresh start as the volumes persist, see #2579

feat(ci): add test for service restart

---

.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml

- do complex tests after basic
- remove matrix where not needed
- sync bledding and normal jobs

feat(ci): sync and structure test deps

---

.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml
Dockerfile

- the wheel no longer includes test dependencies
- we might eventually discard even the test data
- faster publishing of docker image

chore(ci): drop unit testing

---

Dockerfile
requirements.txt

- use base images built separately that contain all system dependencies
- use multistage build to avoid devel deps in the final image

feat: split out docker build

---

.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml
Dockerfile

This removes need to build binary wheels repeatedly.
Fixes #2588

feat: utilize uv CI cache

---

.github/workflows/bleeding.yml
.github/workflows/dockerimage.yml
Dockerfile

This can cause issus in some setups as the content is copied, but some permissions seem to be lost.
Fixes #2816

fix: make sure tmpfs volumes are empty

---

Dockerfile

This reverts commit 384b4de166dd6bf208cddfa6bfaa2489922c2f4c.
These volumes are only intended to be used as tmpfs, but when adding them as VOLUME in Dockerfile, these will end up as real volumes in the swarm mode.
Fixes #2816

Revert "Add /tmp and /run volumes"

---

.github/workflows/dockerimage.yml
start

Docker engine follows symlinks when creating the volume what makes /tmp/localtime read-only. But user has apparently configured timezone in this case so we can skip this step.
@FSeidinger-XI This should fix your issue.

feat: add support for defining localtime via volume

---

start

In the SSL setup the X-Forwarded-For header is created by the built-in nginx server so Weblate should use it unless configured otherwise.
See https://github.com/WeblateOrg/weblate/issues/13325

feat: automatically use X-Forwarded-For from built-in nginx

---

.editorconfig
.github/bin/bleeding
.github/bin/get-buildx-args
.pre-commit-config.yaml
health_check
start

feat(ci): introduce shfmt

---

Dockerfile

This is needed to allow migrating to Python 3.13 as xmlsec does not ship compatible wheels there.

feat: build lxml/xmlsec from source

---

.github/workflows/container-build.yml
.github/workflows/container-ci.yml
.github/workflows/container-test.yml

Pinning the docker/setup-buildx-action should be good enough for us, the buildx was only needed early when we needed newer version than was installed by the action.

chore: remove docker/buildx version pin

---

etc/nginx/default.tpl

This breaks anubis integration because it uses server port (8080) instead of the actual port where the service is exposed.

fix: disable using ports in nginx redirets

---

etc/nginx/default.tpl

Exclude widgets, healt check or RSS feeds.
Fixes https://github.com/WeblateOrg/weblate/issues/14945

fix: exclude some URLs from anubis

---

etc/nginx/default.tpl
etc/supervisor/conf.d/web.conf
requirements.txt
start

- Doesn't fail requests when the worker needs to be restarted in
multi-threaded environment (issue #3507).
- Supports limiting RSS usage reducing number of restarts.
- The WSGI core should perform way better (I don't expect visible impact
on Weblate here, but still it heavily reduces the overhead).
Fixes #3507
Built on top of https://github.com/WeblateOrg/docker/pull/3509 to verify the test is effective.

feat: replace gunicorn with granian

---

etc/supervisor/conf.d/web.conf
start

- switch to st mode as this is mostly deployed with small amount of processes
- revert blocking-threads-idle-timeout as it does not influence what we wanted (see https://github.com/emmett-framework/granian/issues/668)
- avoid manually configuring backpressure and threads, the used value was probably wrong anyway
- dynamically scale workers to have more of them on larger setups

fix: improve granian configuration
